apiVersion: v1
kind: Secret
metadata:
  name: twitter-app-credentials-secret
  namespace: cqrs-demo
type: Opaque
data:
  CONSUMER_KEY: U0hhQjA
  CONSUMER_SECRET: dTBD
  ACCESS_TOKEN_KEY: OTE
  ACCESS_TOKEN_SECRET: aXZv


#echo -n 'value' | base64  

