apiVersion: v1
kind: Secret
metadata:
  name: kafka-server-secret
  namespace: cqrs-demo
type: Opaque
data:
  kafka-server-endpoint: base64 representation of your kafka-server-endpoint
  kafka-topic: base64 representation of your kafka-topic

#echo -n 'value' | base64  
