apiVersion: v1
kind: Secret
metadata:
  name: twitter-app-credentials-secret
  namespace: cqrs-demo
type: Opaque
data:
  CONSUMER_KEY: base64 representation
  CONSUMER_SECRET: base64 representation
  ACCESS_TOKEN_KEY: base64 representation
  ACCESS_TOKEN_SECRET: base64 representation


#echo -n 'value' | base64  

